### ISSUE TITLE
Structural directives (like *ngIf) doesn't work on lazy-loaded components

### ISSUE THREAD

**Issue by 4i-helpynet** [funOfheuristic/lazy-loading-component#1]
Hi.

Due the missing import of CommonModule, the lazy-loaded component fail on structural directives.
If you extend your lazy-comp-a.component.html as this:
`<p>lazy-comp-a works!</p><p *ngIf="true">here</p>`
You'll not see 'here', only a warning in console:

> core.js:12565 Can't bind to 'ngIf' since it isn't a known property of 'p'.

**Comment by funOfheuristic** [comment]
A module can be added in the dame file to get the structural directives working. like the example below.

```
@NgModule({
  declarations: [LazyCompAComponent],
  imports: [CommonModule]
})
class LazyCompAModule {}
```
